#!/usr/bin/env python3
"""Validate the merged tree generated by backbone grafting."""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

from phylo_merge_common import (
    load_backbone_summary,
    load_paml_summary,
    load_table,
    load_target_summary,
    read_newick_tree,
    validate_branch_lengths_complete,
    validate_rooted_binary_tree,
    validate_rooted_tree_with_outgroup,
)
from phylo_split_common import PipelineError, get_tip_names_from_tree, setup_logger, write_validation_report


def run(
    split_output_dir,
    merge_output_dir,
    merge_mode="backbone_graft",
    backbone_edge_aggregation="weighted_geometric_mean",
    log_level="INFO",
    outgroup_tip_name=None,
):
    if merge_mode != "backbone_graft":
        raise PipelineError(f"Unsupported merge.mode: {merge_mode}")
    if backbone_edge_aggregation != "weighted_geometric_mean":
        raise PipelineError(f"Unsupported merge.backbone_edge_aggregation: {backbone_edge_aggregation}")

    split_output_dir = Path(split_output_dir).resolve()
    merge_output_dir = Path(merge_output_dir).resolve()
    logger = setup_logger("validate_merged_tree", None, log_level)
    logger.info("Starting merged tree validation.")

    master_tree_path = split_output_dir / "intermediate" / "rooted.tree"
    scaffold_tree_path = merge_output_dir / "assembly_scaffold.nwk"
    merged_tree_path = merge_output_dir / "merged_tree.nwk"
    if not master_tree_path.exists():
        raise PipelineError(f"Required rooted master tree not found: {master_tree_path}")
    if not scaffold_tree_path.exists():
        raise PipelineError(f"Assembly scaffold not found: {scaffold_tree_path}")
    if not merged_tree_path.exists():
        raise PipelineError(f"Merged tree not found: {merged_tree_path}")

    master_tree = read_newick_tree(master_tree_path)
    scaffold_tree = read_newick_tree(scaffold_tree_path)
    merged_tree = read_newick_tree(merged_tree_path)

    backbone_records = load_backbone_summary(split_output_dir / "backbone_summary.tsv")
    target_records = load_target_summary(split_output_dir / "target_subtree_summary.tsv")
    paml_records = load_paml_summary(split_output_dir / "paml_subtree_summary.tsv")
    if outgroup_tip_name in (None, "", "null"):
        unique_outgroups = sorted({record.outgroup_tip for record in paml_records})
        if len(unique_outgroups) != 1:
            raise PipelineError(
                f"Could not infer a unique outgroup tip from {split_output_dir / 'paml_subtree_summary.tsv'}: {unique_outgroups}"
            )
        outgroup_tip_name = unique_outgroups[0]
    validate_rooted_binary_tree(master_tree, outgroup_tip_name)
    validate_rooted_tree_with_outgroup(scaffold_tree, outgroup_tip_name)
    validate_rooted_tree_with_outgroup(merged_tree, outgroup_tip_name)
    validate_branch_lengths_complete(merged_tree)
    graft_report_rows = load_table(merge_output_dir / "graft_report.tsv")
    edge_update_rows = load_table(merge_output_dir / "edge_update_report.tsv")
    backbone_edge_rows = load_table(merge_output_dir / "backbone_edge_estimates.tsv")

    report_rows = []
    master_tip_names = get_tip_names_from_tree(master_tree)
    scaffold_tip_names = get_tip_names_from_tree(scaffold_tree)
    merged_tip_names = get_tip_names_from_tree(merged_tree)
    backbone_tip_names = [record.backbone_tip_name for record in sorted(backbone_records, key=lambda item: item.selection_rank)]
    placeholder_names = {f"TARGET_{record.target_subtree_id.split('_')[-1]}" for record in target_records}

    expected_scaffold_tips = set(backbone_tip_names) | placeholder_names | {outgroup_tip_name}
    if set(scaffold_tip_names) != expected_scaffold_tips:
        missing = sorted(expected_scaffold_tips - set(scaffold_tip_names))
        extra = sorted(set(scaffold_tip_names) - expected_scaffold_tips)
        report_rows.append(("assembly_scaffold_tip_set", "FAIL", f"missing={missing[:5]} extra={extra[:5]}"))
    else:
        report_rows.append(("assembly_scaffold_tip_set", "PASS", f"{len(scaffold_tip_names)} scaffold tips verified"))

    if set(merged_tip_names) != set(master_tip_names):
        missing = sorted(set(master_tip_names) - set(merged_tip_names))
        extra = sorted(set(merged_tip_names) - set(master_tip_names))
        report_rows.append(("merged_tip_set", "FAIL", f"missing={missing[:5]} extra={extra[:5]}"))
    else:
        report_rows.append(("merged_tip_set", "PASS", f"{len(merged_tip_names)} merged tips verified"))

    target_like = [tip_name for tip_name in merged_tip_names if tip_name.startswith("TARGET_")]
    if target_like:
        report_rows.append(("merged_placeholders_removed", "FAIL", f"Found unresolved placeholders: {target_like[:5]}"))
    else:
        report_rows.append(("merged_placeholders_removed", "PASS", "No TARGET placeholders remain in merged tree"))

    successful_grafts = [row for row in graft_report_rows if row["graft_status"] == "success"]
    if len(successful_grafts) != len(target_records):
        report_rows.append(("graft_report_complete", "FAIL", "Not all target subtrees were grafted successfully"))
    else:
        report_rows.append(("graft_report_complete", "PASS", f"{len(successful_grafts)} target grafts verified"))

    if len({row["target_subtree_id"] for row in successful_grafts}) != len(target_records):
        report_rows.append(("graft_target_uniqueness", "FAIL", "graft_report.tsv target ids are not unique"))
    else:
        report_rows.append(("graft_target_uniqueness", "PASS", "Each target subtree appears exactly once"))

    if not backbone_edge_rows:
        report_rows.append(("backbone_edge_estimates", "FAIL", "backbone_edge_estimates.tsv is empty"))
    else:
        report_rows.append(("backbone_edge_estimates", "PASS", f"{len(backbone_edge_rows)} backbone signatures aggregated"))

    if not any(row["edge_role"] == "target_graft" for row in edge_update_rows):
        report_rows.append(("edge_updates_have_grafts", "FAIL", "edge_update_report.tsv does not record target_graft rows"))
    else:
        report_rows.append(("edge_updates_have_grafts", "PASS", "target_graft edge updates recorded"))

    report_rows.append(("merged_rooted_topology", "PASS", "Merged tree remains rooted with a singleton outgroup"))
    report_rows.append(("merged_branch_lengths_complete", "PASS", "All non-root branches have non-negative lengths"))

    write_validation_report(report_rows, merge_output_dir / "merge_validation_report.tsv")
    failures = [row for row in report_rows if row[1] == "FAIL"]
    if failures:
        details = "; ".join(f"{name}: {detail}" for name, _, detail in failures[:10])
        raise PipelineError(f"Merged tree validation failed with {len(failures)} issue(s): {details}")
    logger.info("Merged tree validation passed.")
    return 0


def build_parser():
    parser = argparse.ArgumentParser(description="Validate the merged tree from backbone graft outputs.")
    parser.add_argument("--split-output-dir", required=True, help="Output directory from the split pipeline.")
    parser.add_argument("--merge-output-dir", required=True, help="Merge output directory.")
    parser.add_argument("--merge-mode", default="backbone_graft", help="Merge mode.")
    parser.add_argument("--backbone-edge-aggregation", default="weighted_geometric_mean", help="Backbone edge aggregation strategy.")
    parser.add_argument("--log-level", default="INFO", help="Logging level.")
    parser.add_argument("--outgroup-tip-name", default=None, help="Singleton outgroup tip retained at the root.")
    return parser


def main(argv=None):
    parser = build_parser()
    args = parser.parse_args(argv)
    try:
        return run(
            split_output_dir=args.split_output_dir,
            merge_output_dir=args.merge_output_dir,
            merge_mode=args.merge_mode,
            backbone_edge_aggregation=args.backbone_edge_aggregation,
            log_level=args.log_level,
            outgroup_tip_name=args.outgroup_tip_name,
        )
    except PipelineError as exc:
        print(f"[ERROR] {exc}", file=sys.stderr)
        return 1


if __name__ == "__main__":
    raise SystemExit(main())
